FROM python:3.12-slim

WORKDIR /src

COPY requirements_gradio.txt /src/

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
    gcc \
&& rm -rf /var/lib/apt/lists/* \
&& rm -rf /root/.cache \
&& pip install --upgrade pip \
&& pip install --no-cache-dir -r requirements_gradio.txt 

COPY . /src/

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"
ENV GRADIO_SERVER_PORT="7860"
# ENV HUGGING_FACE_HUB_TOKEN=$HF_TOKEN